CC = g++
CFLAGS = -std=c++17

TARGET = DiskSchedulingAlgorithm

all: $(TARGET)

$(TARGET): DiskSchedulingAlgorithm.cpp
	$(CC) $(CFLAGS) -o $(TARGET) DiskSchedulingAlgorithm.cpp

clean:
	rm -f $(TARGET)
